import { useState } from "react";
import { BarChart3, Download, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

const reportTypes = ["Network health summary", "Anomaly performance", "Station reliability", "Maintenance backlog"];
export function Reports() {
  const [report, setReport] = useState(reportTypes[0]);
  const [range, setRange] = useState("Last 7 days");
  const [exported, setExported] = useState(false);
  return <div className="space-y-6"><div><h1 className="font-serif text-2xl font-bold text-ink-navy">Reports</h1><p className="mt-1 text-sm text-graphite/70">Build focused operational reports without leaving the monitoring workspace.</p></div><Card className="p-5"><div className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-deep-atmo" /><h2 className="font-semibold text-ink-navy">Report builder</h2></div><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="space-y-1.5 text-sm font-medium text-graphite">Report type<select value={report} onChange={(event) => setReport(event.target.value)} className="mt-1 flex h-10 w-full rounded-lg border border-cloud-grey bg-white px-3 text-sm text-graphite">{reportTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label className="space-y-1.5 text-sm font-medium text-graphite">Time range<select value={range} onChange={(event) => setRange(event.target.value)} className="mt-1 flex h-10 w-full rounded-lg border border-cloud-grey bg-white px-3 text-sm text-graphite"><option>Last 24 hours</option><option>Last 7 days</option><option>Last 30 days</option><option>This quarter</option></select></label></div><div className="mt-5 flex flex-wrap items-center gap-3"><Button onClick={() => setExported(true)}><Download className="mr-2 h-4 w-4" /> Export report</Button>{exported && <span className="text-sm text-healthy-green">Report queued for download.</span>}</div></Card><div className="grid gap-4 md:grid-cols-3"><Card className="p-5"><FileText className="h-5 w-5 text-sky-blue" /><p className="mt-4 text-xs text-graphite/60">Selected report</p><p className="mt-1 font-semibold text-ink-navy">{report}</p></Card><Card className="p-5"><p className="text-xs text-graphite/60">Coverage</p><p className="mt-1 text-2xl font-bold text-ink-navy">128</p><p className="text-xs text-graphite/60">stations included</p></Card><Card className="p-5"><p className="text-xs text-graphite/60">Period</p><p className="mt-1 font-semibold text-ink-navy">{range}</p><p className="text-xs text-graphite/60">current workspace</p></Card></div></div>;
}
