// Generated by scripts/gen-imd-stations.mjs — DO NOT EDIT BY HAND.
// Reduced IMD network: 131 representative stations (3-4 per state/UT),
//   trimmed from the 1150-station ShagunDwivedi/IndianWeatherAPI city list — state capital
//   and major cities first, then geographically-spread AWS.
// Coordinates are verified station locations (approximate = deterministic fallback).
export type ImdRegion = "north" | "south" | "east" | "west" | "central" | "northeast";

export interface ImdStation {
  id: string;
  slug: string;
  name: string;
  state: string;
  district: string;
  region: ImdRegion;
  imdId: string;
  latitude: number;
  longitude: number;
  approximate: boolean;
}

const INDIA_BOUNDS = {
  latMin: 6.0,
  latMax: 37.7,
  lngMin: 67.5,
  lngMax: 97.5,
};

function isWithinIndia(station: ImdStation): boolean {
  return (
    station.latitude >= INDIA_BOUNDS.latMin &&
    station.latitude <= INDIA_BOUNDS.latMax &&
    station.longitude >= INDIA_BOUNDS.lngMin &&
    station.longitude <= INDIA_BOUNDS.lngMax
  );
}

function deduplicateByCoords(arr: ImdStation[]): ImdStation[] {
  const seen = new Set<string>();
  return arr.filter((station) => {
    const key = `${station.latitude.toFixed(3)},${station.longitude.toFixed(3)}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

const rawImdStations: ImdStation[] = [
  { id: "IMD-42701", slug: "ranchi", name: "Ranchi", state: "Jharkhand", district: "Ranchi", region: "east", imdId: "42701", latitude: 23.3441, longitude: 85.3096, approximate: false },
  { id: "IMD-42798", slug: "jamshedpur", name: "Jamshedpur", state: "Jharkhand", district: "Jamshedpur", region: "east", imdId: "42798", latitude: 22.8046, longitude: 86.2029, approximate: false },
  { id: "IMD-100002", slug: "dhanbad", name: "Dhanbad", state: "Jharkhand", district: "Dhanbad", region: "east", imdId: "100002", latitude: 23.7957, longitude: 86.4304, approximate: false },
  { id: "IMD-100005", slug: "hazaribagh", name: "Hazaribagh", state: "Jharkhand", district: "Hazaribagh", region: "east", imdId: "100005", latitude: 23.99241, longitude: 85.36162, approximate: false },
  { id: "IMD-10001", slug: "faridabad", name: "Faridabad", state: "Haryana", district: "Faridabad", region: "north", imdId: "10001", latitude: 28.4089, longitude: 77.3178, approximate: false },
  { id: "IMD-42178", slug: "gurgaon", name: "Gurgaon", state: "Haryana", district: "Gurgaon", region: "north", imdId: "42178", latitude: 28.4595, longitude: 77.0266, approximate: false },
  { id: "IMD-42137", slug: "karnal", name: "Karnal", state: "Haryana", district: "Karnal", region: "north", imdId: "42137", latitude: 29.69197, longitude: 76.98448, approximate: false },
  { id: "IMD-30025", slug: "panipat", name: "Panipat", state: "Haryana", district: "Panipat", region: "north", imdId: "30025", latitude: 29.38747, longitude: 76.96825, approximate: false },
  { id: "IMD-43295", slug: "bengaluru-city", name: "Bengaluru City", state: "Karnataka", district: "City", region: "south", imdId: "43295", latitude: 12.9716, longitude: 77.5946, approximate: false },
  { id: "IMD-43291", slug: "mysuru", name: "Mysuru", state: "Karnataka", district: "Mysuru", region: "south", imdId: "43291", latitude: 12.2958, longitude: 76.6394, approximate: false },
  { id: "IMD-43284", slug: "mangaluru", name: "Mangaluru", state: "Karnataka", district: "Mangaluru", region: "south", imdId: "43284", latitude: 12.91723, longitude: 74.85603, approximate: false },
  { id: "IMD-43198", slug: "belagavi", name: "Belagavi", state: "Karnataka", district: "Belagavi", region: "south", imdId: "43198", latitude: 15.8497, longitude: 74.4977, approximate: false },
  { id: "IMD-99969", slug: "jaipur-amer", name: "Jaipur Amer", state: "Rajasthan", district: "Amer", region: "north", imdId: "99969", latitude: 26.9124, longitude: 75.7873, approximate: false },
  { id: "IMD-42339", slug: "jodhpur", name: "Jodhpur", state: "Rajasthan", district: "Jodhpur", region: "north", imdId: "42339", latitude: 26.2389, longitude: 73.0243, approximate: false },
  { id: "IMD-42452", slug: "kota", name: "Kota", state: "Rajasthan", district: "Kota", region: "north", imdId: "42452", latitude: 25.2138, longitude: 75.8648, approximate: false },
  { id: "IMD-42542", slug: "udaipur", name: "Udaipur", state: "Rajasthan", district: "Udaipur", region: "north", imdId: "42542", latitude: 24.5854, longitude: 73.7125, approximate: false },
  { id: "IMD-42970", slug: "bhubneshwar-cuttack", name: "Bhubneshwar Cuttack", state: "Odisha", district: "Cuttack", region: "east", imdId: "42970", latitude: 20.2961, longitude: 85.8245, approximate: false },
  { id: "IMD-42883", slug: "sambalpur", name: "Sambalpur", state: "Odisha", district: "Sambalpur", region: "east", imdId: "42883", latitude: 21.4669, longitude: 83.9812, approximate: false },
  { id: "IMD-42895", slug: "balasore", name: "Balasore", state: "Odisha", district: "Balasore", region: "east", imdId: "42895", latitude: 21.49266, longitude: 86.93348, approximate: false },
  { id: "IMD-100402", slug: "malkangiri", name: "Malkangiri", state: "Odisha", district: "Malkangiri", region: "east", imdId: "100402", latitude: 18.353, longitude: 81.8772, approximate: false },
  { id: "IMD-42369", slug: "lucknow-airport", name: "Lucknow Airport", state: "Uttar Pradesh", district: "Airport", region: "north", imdId: "42369", latitude: 26.8467, longitude: 80.9462, approximate: false },
  { id: "IMD-42366", slug: "kanpur", name: "Kanpur", state: "Uttar Pradesh", district: "Kanpur", region: "north", imdId: "42366", latitude: 26.4499, longitude: 80.3319, approximate: false },
  { id: "IMD-42260", slug: "agra", name: "Agra", state: "Uttar Pradesh", district: "Agra", region: "north", imdId: "42260", latitude: 27.1767, longitude: 78.0081, approximate: false },
  { id: "IMD-42479", slug: "varanasi", name: "Varanasi", state: "Uttar Pradesh", district: "Varanasi", region: "north", imdId: "42479", latitude: 25.3176, longitude: 82.9739, approximate: false },
  { id: "IMD-99941", slug: "mumbai-borivali", name: "Mumbai Borivali", state: "Maharashtra", district: "Borivali", region: "west", imdId: "99941", latitude: 19.2307, longitude: 72.8567, approximate: false },
  { id: "IMD-43064", slug: "pune-lohegaon airport", name: "Pune Lohegaon airport", state: "Maharashtra", district: "Lohegaon airport", region: "west", imdId: "43064", latitude: 18.5821, longitude: 73.9197, approximate: false },
  { id: "IMD-99982", slug: "nagpur-college of agriculture", name: "Nagpur College of agriculture", state: "Maharashtra", district: "College of agriculture", region: "west", imdId: "99982", latitude: 21.1458, longitude: 79.0882, approximate: false },
  { id: "IMD-43158", slug: "sangli", name: "Sangli", state: "Maharashtra", district: "Sangli", region: "west", imdId: "43158", latitude: 16.85438, longitude: 74.56417, approximate: false },
  { id: "IMD-99954", slug: "dehradun-asharori", name: "Dehradun Asharori", state: "Uttarakhand", district: "Asharori", region: "north", imdId: "99954", latitude: 30.3165, longitude: 78.0322, approximate: false },
  { id: "IMD-99918", slug: "haridwar", name: "Haridwar", state: "Uttarakhand", district: "Haridwar", region: "north", imdId: "99918", latitude: 29.94791, longitude: 78.16025, approximate: false },
  { id: "IMD-42146", slug: "nainital", name: "Nainital", state: "Uttarakhand", district: "Nainital", region: "north", imdId: "42146", latitude: 29.39743, longitude: 79.44686, approximate: false },
  { id: "IMD-100217", slug: "haldwani", name: "Haldwani", state: "Uttarakhand", district: "Haldwani", region: "north", imdId: "100217", latitude: 29.22254, longitude: 79.5286, approximate: false },
  { id: "IMD-42807", slug: "kolkata-alipur", name: "Kolkata Alipur", state: "West Bengal", district: "Alipur", region: "east", imdId: "42807", latitude: 22.5352, longitude: 88.3319, approximate: false },
  { id: "IMD-42397", slug: "siliguri", name: "Siliguri", state: "West Bengal", district: "Siliguri", region: "east", imdId: "42397", latitude: 26.7271, longitude: 88.3953, approximate: false },
  { id: "IMD-42704", slug: "asansol", name: "Asansol", state: "West Bengal", district: "Asansol", region: "east", imdId: "42704", latitude: 23.68333, longitude: 86.98333, approximate: false },
  { id: "IMD-42503", slug: "malda", name: "Malda", state: "West Bengal", district: "Malda", region: "east", imdId: "42503", latitude: 25.00447, longitude: 88.14573, approximate: false },
  { id: "IMD-99974", slug: "raipur-labhandi", name: "Raipur Labhandi", state: "Chhattisgarh", district: "Labhandi", region: "central", imdId: "99974", latitude: 21.2514, longitude: 81.6296, approximate: false },
  { id: "IMD-42080", slug: "bilaspur", name: "Bilaspur", state: "Chhattisgarh", district: "Bilaspur", region: "central", imdId: "42080", latitude: 22.08005, longitude: 82.15543, approximate: false },
  { id: "IMD-100250", slug: "patelpali raigarh", name: "Patelpali raigarh", state: "Chhattisgarh", district: "Patelpali raigarh", region: "central", imdId: "100250", latitude: 21.8974, longitude: 83.395, approximate: false },
  { id: "IMD-100249", slug: "navapara", name: "Navapara", state: "Chhattisgarh", district: "Navapara", region: "central", imdId: "100249", latitude: 18.628, longitude: 81.62508, approximate: false },
  { id: "IMD-42654", slug: "gandhinagar", name: "Gandhinagar", state: "Gujarat", district: "Gandhinagar", region: "west", imdId: "42654", latitude: 23.21667, longitude: 72.68333, approximate: false },
  { id: "IMD-42647", slug: "ahmedabad", name: "Ahmedabad", state: "Gujarat", district: "Ahmedabad", region: "west", imdId: "42647", latitude: 23.0225, longitude: 72.5714, approximate: false },
  { id: "IMD-42840", slug: "surat", name: "Surat", state: "Gujarat", district: "Surat", region: "west", imdId: "42840", latitude: 21.19594, longitude: 72.83023, approximate: false },
  { id: "IMD-42737", slug: "rajkot", name: "Rajkot", state: "Gujarat", district: "Rajkot", region: "west", imdId: "42737", latitude: 22.29161, longitude: 70.79322, approximate: false },
  { id: "IMD-42027", slug: "srinagar-city", name: "Srinagar City", state: "Jammu & Kashmir", district: "City", region: "north", imdId: "42027", latitude: 34.0837, longitude: 74.7973, approximate: false },
  { id: "IMD-42056", slug: "jammu-city", name: "Jammu City", state: "Jammu & Kashmir", district: "City", region: "north", imdId: "42056", latitude: 32.73528, longitude: 74.86167, approximate: false },
  { id: "IMD-90027", slug: "udhampur", name: "Udhampur", state: "Jammu & Kashmir", district: "Udhampur", region: "north", imdId: "90027", latitude: 32.92431, longitude: 75.13573, approximate: false },
  { id: "IMD-90020", slug: "anantnag", name: "Anantnag", state: "Jammu & Kashmir", district: "Anantnag", region: "north", imdId: "90020", latitude: 33.73068, longitude: 75.15418, approximate: false },
  { id: "IMD-99977", slug: "bhopal-airport", name: "Bhopal Airport", state: "Madhya Pradesh", district: "Airport", region: "central", imdId: "99977", latitude: 23.2599, longitude: 77.4126, approximate: false },
  { id: "IMD-42754", slug: "indore", name: "Indore", state: "Madhya Pradesh", district: "Indore", region: "central", imdId: "42754", latitude: 22.7196, longitude: 75.8577, approximate: false },
  { id: "IMD-42675", slug: "jabalpur", name: "Jabalpur", state: "Madhya Pradesh", district: "Jabalpur", region: "central", imdId: "42675", latitude: 23.16697, longitude: 79.95006, approximate: false },
  { id: "IMD-42361", slug: "gwalior", name: "Gwalior", state: "Madhya Pradesh", district: "Gwalior", region: "central", imdId: "42361", latitude: 26.22983, longitude: 78.17337, approximate: false },
  { id: "IMD-43328", slug: "pondicherry", name: "Pondicherry", state: "Puducherry", district: "Pondicherry", region: "south", imdId: "43328", latitude: 11.9416, longitude: 79.8083, approximate: false },
  { id: "IMD-100411", slug: "thattanchavady", name: "Thattanchavady", state: "Puducherry", district: "Thattanchavady", region: "south", imdId: "100411", latitude: 11.935, longitude: 79.812, approximate: false },
  { id: "IMD-43346", slug: "karaikal", name: "Karaikal", state: "Puducherry", district: "Karaikal", region: "south", imdId: "43346", latitude: 10.91667, longitude: 79.83333, approximate: false },
  { id: "IMD-42099", slug: "ludhiana", name: "Ludhiana", state: "Punjab", district: "Ludhiana", region: "north", imdId: "42099", latitude: 30.91204, longitude: 75.85379, approximate: false },
  { id: "IMD-42071", slug: "amritsar", name: "Amritsar", state: "Punjab", district: "Amritsar", region: "north", imdId: "42071", latitude: 31.634, longitude: 74.8723, approximate: false },
  { id: "IMD-42075", slug: "jalandhar", name: "Jalandhar", state: "Punjab", district: "Jalandhar", region: "north", imdId: "42075", latitude: 31.32556, longitude: 75.57917, approximate: false },
  { id: "IMD-42101", slug: "patiala", name: "Patiala", state: "Punjab", district: "Patiala", region: "north", imdId: "42101", latitude: 30.33625, longitude: 76.3922, approximate: false },
  { id: "IMD-99948", slug: "chennai-ennore", name: "Chennai Ennore", state: "Tamil Nadu", district: "Ennore", region: "south", imdId: "99948", latitude: 13.2167, longitude: 80.3167, approximate: false },
  { id: "IMD-43321", slug: "coimbatore", name: "Coimbatore", state: "Tamil Nadu", district: "Coimbatore", region: "south", imdId: "43321", latitude: 11.0168, longitude: 76.9558, approximate: false },
  { id: "IMD-43360", slug: "madurai", name: "Madurai", state: "Tamil Nadu", district: "Madurai", region: "south", imdId: "43360", latitude: 9.9252, longitude: 78.1198, approximate: false },
  { id: "IMD-43325", slug: "salem", name: "Salem", state: "Tamil Nadu", district: "Salem", region: "south", imdId: "43325", latitude: 11.65376, longitude: 78.15538, approximate: false },
  { id: "IMD-43128", slug: "hyderabad", name: "Hyderabad", state: "Telangana", district: "Hyderabad", region: "south", imdId: "43128", latitude: 17.385, longitude: 78.4867, approximate: false },
  { id: "IMD-99925", slug: "warangal", name: "Warangal", state: "Telangana", district: "Warangal", region: "south", imdId: "99925", latitude: 17.9784, longitude: 79.5941, approximate: false },
  { id: "IMD-43081", slug: "nizamabad", name: "Nizamabad", state: "Telangana", district: "Nizamabad", region: "south", imdId: "43081", latitude: 18.6725, longitude: 78.094, approximate: false },
  { id: "IMD-100521", slug: "karimnagar", name: "Karimnagar", state: "Telangana", district: "Karimnagar", region: "south", imdId: "100521", latitude: 18.43915, longitude: 79.12856, approximate: false },
  { id: "IMD-42083", slug: "shimla-city", name: "Shimla City", state: "Himachal Pradesh", district: "City", region: "north", imdId: "42083", latitude: 31.1048, longitude: 77.1734, approximate: false },
  { id: "IMD-42081", slug: "kullu", name: "Kullu", state: "Himachal Pradesh", district: "Kullu", region: "north", imdId: "42081", latitude: 31.95835, longitude: 77.10823, approximate: false },
  { id: "IMD-42106", slug: "solan", name: "Solan", state: "Himachal Pradesh", district: "Solan", region: "north", imdId: "42106", latitude: 30.90908, longitude: 77.10869, approximate: false },
  { id: "IMD-42076", slug: "kangra", name: "Kangra", state: "Himachal Pradesh", district: "Kangra", region: "north", imdId: "42076", latitude: 32.09135, longitude: 76.26267, approximate: false },
  { id: "IMD-42299", slug: "gangtok", name: "Gangtok", state: "Sikkim", district: "Gangtok", region: "east", imdId: "42299", latitude: 27.3389, longitude: 88.6065, approximate: false },
  { id: "IMD-26003", slug: "namchi", name: "Namchi", state: "Sikkim", district: "Namchi", region: "east", imdId: "26003", latitude: 27.16494, longitude: 88.3638, approximate: false },
  { id: "IMD-30023", slug: "lachung", name: "Lachung", state: "Sikkim", district: "Lachung", region: "east", imdId: "30023", latitude: 27.6934, longitude: 88.74429, approximate: false },
  { id: "IMD-101042", slug: "teesta iii", name: "Teesta iii", state: "Sikkim", district: "Teesta iii", region: "east", imdId: "101042", latitude: 27.603, longitude: 88.65, approximate: false },
  { id: "IMD-42308", slug: "itanagar", name: "Itanagar", state: "Arunachal Pradesh", district: "Itanagar", region: "northeast", imdId: "42308", latitude: 27.1044, longitude: 93.692, approximate: false },
  { id: "IMD-101012", slug: "kameng-bichom dam", name: "Kameng Bichom dam", state: "Arunachal Pradesh", district: "Bichom dam", region: "northeast", imdId: "101012", latitude: 27.0526, longitude: 92.4947, approximate: false },
  { id: "IMD-42220", slug: "passighat", name: "Passighat", state: "Arunachal Pradesh", district: "Passighat", region: "northeast", imdId: "42220", latitude: 28.0667, longitude: 95.3333, approximate: false },
  { id: "IMD-101027", slug: "ranganadi", name: "Ranganadi", state: "Arunachal Pradesh", district: "Ranganadi", region: "northeast", imdId: "101027", latitude: 27.3361, longitude: 93.9761, approximate: false },
  { id: "IMD-42726", slug: "aizwal", name: "Aizwal", state: "Mizoram", district: "Aizwal", region: "northeast", imdId: "42726", latitude: 23.72894, longitude: 92.71791, approximate: false },
  { id: "IMD-88828", slug: "lunglei", name: "Lunglei", state: "Mizoram", district: "Lunglei", region: "northeast", imdId: "88828", latitude: 22.89247, longitude: 92.74218, approximate: false },
  { id: "IMD-19001", slug: "champhai", name: "Champhai", state: "Mizoram", district: "Champhai", region: "northeast", imdId: "19001", latitude: 23.4728, longitude: 93.3294, approximate: false },
  { id: "IMD-42727", slug: "aizwal-lengpui", name: "Aizwal Lengpui", state: "Mizoram", district: "Lengpui", region: "northeast", imdId: "42727", latitude: 23.84, longitude: 92.6197, approximate: false },
  { id: "IMD-42527", slug: "kohima", name: "Kohima", state: "Nagaland", district: "Kohima", region: "northeast", imdId: "42527", latitude: 25.6586, longitude: 94.1086, approximate: false },
  { id: "IMD-21002", slug: "mokokchung", name: "Mokokchung", state: "Nagaland", district: "Mokokchung", region: "northeast", imdId: "21002", latitude: 26.3248, longitude: 94.51834, approximate: false },
  { id: "IMD-21001", slug: "kohima-dimapur", name: "Kohima Dimapur", state: "Nagaland", district: "Dimapur", region: "northeast", imdId: "21001", latitude: 25.902, longitude: 93.726, approximate: false },
  { id: "IMD-88832", slug: "kargil", name: "Kargil", state: "Ladakh", district: "Kargil", region: "north", imdId: "88832", latitude: 34.55765, longitude: 76.12622, approximate: false },
  { id: "IMD-30003", slug: "diskit nubra", name: "Diskit nubra", state: "Ladakh", district: "Diskit nubra", region: "north", imdId: "30003", latitude: 34.55, longitude: 77.5667, approximate: false },
  { id: "IMD-42034", slug: "leh", name: "Leh", state: "Ladakh", district: "Leh", region: "north", imdId: "42034", latitude: 34.1526, longitude: 77.5771, approximate: false },
  { id: "IMD-43371", slug: "thiruvananthapuram-city", name: "Thiruvananthapuram City", state: "Kerala", district: "City", region: "south", imdId: "43371", latitude: 8.5241, longitude: 76.9366, approximate: false },
  { id: "IMD-43314", slug: "kozhikode", name: "Kozhikode", state: "Kerala", district: "Kozhikode", region: "south", imdId: "43314", latitude: 11.24802, longitude: 75.7804, approximate: false },
  { id: "IMD-30008", slug: "kollam", name: "Kollam", state: "Kerala", district: "Kollam", region: "south", imdId: "30008", latitude: 8.88113, longitude: 76.58469, approximate: false },
  { id: "IMD-43315", slug: "kannur", name: "Kannur", state: "Kerala", district: "Kannur", region: "south", imdId: "43315", latitude: 11.86752, longitude: 75.35763, approximate: false },
  { id: "IMD-42492", slug: "patna-airport", name: "Patna Airport", state: "Bihar", district: "Airport", region: "east", imdId: "42492", latitude: 25.6093, longitude: 85.1376, approximate: false },
  { id: "IMD-42591", slug: "gaya", name: "Gaya", state: "Bihar", district: "Gaya", region: "east", imdId: "42591", latitude: 24.7953, longitude: 85.0043, approximate: false },
  { id: "IMD-42387", slug: "muzaffarpur", name: "Muzaffarpur", state: "Bihar", district: "Muzaffarpur", region: "east", imdId: "42387", latitude: 26.1209, longitude: 85.3647, approximate: false },
  { id: "IMD-42498", slug: "bhagalpur", name: "Bhagalpur", state: "Bihar", district: "Bhagalpur", region: "east", imdId: "42498", latitude: 25.2425, longitude: 86.9842, approximate: false },
  { id: "IMD-42410", slug: "guwahati", name: "Guwahati", state: "Assam", district: "Guwahati", region: "northeast", imdId: "42410", latitude: 26.1445, longitude: 91.7362, approximate: false },
  { id: "IMD-42619", slug: "silchar", name: "Silchar", state: "Assam", district: "Silchar", region: "northeast", imdId: "42619", latitude: 24.82733, longitude: 92.79787, approximate: false },
  { id: "IMD-42314", slug: "dibrugarh", name: "Dibrugarh", state: "Assam", district: "Dibrugarh", region: "northeast", imdId: "42314", latitude: 27.4728, longitude: 94.912, approximate: false },
  { id: "IMD-42415", slug: "tezpur", name: "Tezpur", state: "Assam", district: "Tezpur", region: "northeast", imdId: "42415", latitude: 26.6528, longitude: 92.7926, approximate: false },
  { id: "IMD-42105", slug: "chandigarh-city", name: "Chandigarh City", state: "Chandigarh", district: "City", region: "north", imdId: "42105", latitude: 30.7333, longitude: 76.7794, approximate: false },
  { id: "IMD-99930", slug: "chandigarh-mohali", name: "Chandigarh Mohali", state: "Chandigarh", district: "Mohali", region: "north", imdId: "99930", latitude: 30.7046, longitude: 76.7179, approximate: false },
  { id: "IMD-99929", slug: "chandigarh-panchkula", name: "Chandigarh Panchkula", state: "Chandigarh", district: "Panchkula", region: "north", imdId: "99929", latitude: 30.6942, longitude: 76.8606, approximate: false },
  { id: "IMD-42180", slug: "new delhi-ayanagar", name: "New delhi Ayanagar", state: "Delhi", district: "Ayanagar", region: "north", imdId: "42180", latitude: 28.5006, longitude: 77.1331, approximate: false },
  { id: "IMD-90144", slug: "najafgarh", name: "Najafgarh", state: "Delhi", district: "Najafgarh", region: "north", imdId: "90144", latitude: 28.60922, longitude: 76.97982, approximate: false },
  { id: "IMD-90145", slug: "pitampura", name: "Pitampura", state: "Delhi", district: "Pitampura", region: "north", imdId: "90145", latitude: 28.68964, longitude: 77.13126, approximate: false },
  { id: "IMD-42516", slug: "shillong", name: "Shillong", state: "Meghalaya", district: "Shillong", region: "northeast", imdId: "42516", latitude: 25.5788, longitude: 91.8933, approximate: false },
  { id: "IMD-42515", slug: "cherrapunji", name: "Cherrapunji", state: "Meghalaya", district: "Cherrapunji", region: "northeast", imdId: "42515", latitude: 25.2833, longitude: 91.7333, approximate: false },
  { id: "IMD-42724", slug: "agartala", name: "Agartala", state: "Tripura", district: "Agartala", region: "northeast", imdId: "42724", latitude: 23.8315, longitude: 91.2868, approximate: false },
  { id: "IMD-42618", slug: "kailashahar", name: "Kailashahar", state: "Tripura", district: "Kailashahar", region: "northeast", imdId: "42618", latitude: 24.33199, longitude: 92.00391, approximate: false },
  { id: "IMD-42623", slug: "imphal", name: "Imphal", state: "Manipur", district: "Imphal", region: "northeast", imdId: "42623", latitude: 24.817, longitude: 93.9368, approximate: false },
  { id: "IMD-42916", slug: "daman", name: "Daman", state: "Dadra & Nagar Haveli and Daman & Diu", district: "Daman", region: "west", imdId: "42916", latitude: 20.3974, longitude: 72.8359, approximate: false },
  { id: "IMD-42914", slug: "diu", name: "Diu", state: "Dadra & Nagar Haveli and Daman & Diu", district: "Diu", region: "west", imdId: "42914", latitude: 20.71405, longitude: 70.98224, approximate: false },
  { id: "IMD-43176", slug: "amaravati-ap", name: "Amaravati Ap", state: "Andhra Pradesh", district: "Ap", region: "south", imdId: "43176", latitude: 16.514, longitude: 80.516, approximate: false },
  { id: "IMD-43150", slug: "visakhapatnam", name: "Visakhapatnam", state: "Andhra Pradesh", district: "Visakhapatnam", region: "south", imdId: "43150", latitude: 17.6868, longitude: 83.2185, approximate: false },
  { id: "IMD-43181", slug: "vijayawada-gannavaram", name: "Vijayawada Gannavaram", state: "Andhra Pradesh", district: "Gannavaram", region: "south", imdId: "43181", latitude: 16.5062, longitude: 80.648, approximate: false },
  { id: "IMD-43213", slug: "kurnool", name: "Kurnool", state: "Andhra Pradesh", district: "Kurnool", region: "south", imdId: "43213", latitude: 15.82887, longitude: 78.03602, approximate: false },
  { id: "IMD-43192", slug: "panjim", name: "Panjim", state: "Goa", district: "Panjim", region: "west", imdId: "43192", latitude: 15.49574, longitude: 73.82624, approximate: false },
  { id: "IMD-99983", slug: "panjim-pernem", name: "Panjim Pernem", state: "Goa", district: "Pernem", region: "west", imdId: "99983", latitude: 15.7199, longitude: 73.7952, approximate: false },
  { id: "IMD-99985", slug: "panjim-old goa", name: "Panjim Old goa", state: "Goa", district: "Old goa", region: "west", imdId: "99985", latitude: 15.5009, longitude: 73.912, approximate: false },
  { id: "IMD-99984", slug: "panjim-mapusa", name: "Panjim Mapusa", state: "Goa", district: "Mapusa", region: "west", imdId: "99984", latitude: 15.5937, longitude: 73.8142, approximate: false },
  { id: "IMD-43367", slug: "carnicobar", name: "Carnicobar", state: "Andaman & Nicobar Islands", district: "Carnicobar", region: "south", imdId: "43367", latitude: 9.152, longitude: 92.82, approximate: false },
  { id: "IMD-43333", slug: "port blair", name: "Port blair", state: "Andaman & Nicobar Islands", district: "Port blair", region: "south", imdId: "43333", latitude: 11.6234, longitude: 92.7265, approximate: false },
  { id: "IMD-43309", slug: "maya bandar", name: "Maya bandar", state: "Andaman & Nicobar Islands", district: "Maya bandar", region: "south", imdId: "43309", latitude: 12.9167, longitude: 92.9, approximate: false },
  { id: "IMD-43382", slug: "nancowrie", name: "Nancowrie", state: "Andaman & Nicobar Islands", district: "Nancowrie", region: "south", imdId: "43382", latitude: 7.9919, longitude: 93.5489, approximate: false },
  { id: "IMD-43337", slug: "kavarati", name: "Kavarati", state: "Lakshadweep", district: "Kavarati", region: "south", imdId: "43337", latitude: 10.5669, longitude: 72.642, approximate: false },
  { id: "IMD-43311", slug: "amini divi", name: "Amini divi", state: "Lakshadweep", district: "Amini divi", region: "south", imdId: "43311", latitude: 11.1239, longitude: 72.7258, approximate: false },
  { id: "IMD-43369", slug: "minicoy", name: "Minicoy", state: "Lakshadweep", district: "Minicoy", region: "south", imdId: "43369", latitude: 8.28899, longitude: 73.0617, approximate: false },
  { id: "IMD-88816", slug: "silvassa", name: "Silvassa", state: "Dadra & Nagar Haveli and Daman & Diu", district: "Silvassa", region: "west", imdId: "88816", latitude: 20.27386, longitude: 72.99673, approximate: false },
  { id: "IMD-99964", slug: "dadra & nagar haveli", name: "Dadra & nagar haveli", state: "Dadra & Nagar Haveli and Daman & Diu", district: "Dadra & nagar haveli", region: "west", imdId: "99964", latitude: 20.269, longitude: 72.947, approximate: false }
];

export const imdStations = deduplicateByCoords(rawImdStations.filter(isWithinIndia));

// scripts/gen-imd-stations.mjs bakes verified coordinates straight into
// rawImdStations, so no runtime post-processing is needed here.

export const IMD_STATION_COUNT = imdStations.length;

// ---------------------------------------------------------------------------
// Dev-time catalog integrity check (no-op in production builds).
// Surfaces duplicate ids / duplicate coordinates early instead of causing
// confusing downstream bugs (e.g. React key collisions on the map, stations
// overwriting each other's readings in the weather bulk fetch).
// ---------------------------------------------------------------------------
function assertUniqueCatalog(stations: ImdStation[]): void {
  const idCounts = new Map<string, number>();
  const coordCounts = new Map<string, number>();
  for (const s of stations) {
    idCounts.set(s.id, (idCounts.get(s.id) ?? 0) + 1);
    const coordKey = `${s.latitude.toFixed(3)},${s.longitude.toFixed(3)}`;
    coordCounts.set(coordKey, (coordCounts.get(coordKey) ?? 0) + 1);
  }
  const dupIds = [...idCounts.entries()].filter(([, n]) => n > 1);
  const dupCoords = [...coordCounts.entries()].filter(([, n]) => n > 1);
  if (dupIds.length > 0) {
    console.warn(
      `[imd-stations] ${dupIds.length} duplicate station id(s), e.g. ${dupIds
        .slice(0, 5)
        .map(([id, n]) => `"${id}" x${n}`)
        .join(", ")}`,
    );
  }
  if (dupCoords.length > 0) {
    console.warn(
      `[imd-stations] ${dupCoords.length} duplicate coordinate group(s), e.g. ${dupCoords
        .slice(0, 5)
        .map(([c, n]) => `(${c}) x${n}`)
        .join(", ")}`,
    );
  }
}

if (import.meta.env.DEV) {
  assertUniqueCatalog(imdStations);
}
